AddEventHandler("vorp:SelectedCharacter", SelectedCharacterHandler)
AddEventHandler("vorp:initNewCharacter", SelectedCharacterHandler)
AddEventHandler("playerDropped", PlayerDroppedHandler)
AddEventHandler("onResourceStart", ResourceStartHandler)
AddEventHandler("onResourceStop", ResourceStopHandler)
RegisterCommand("playtime", PlaytimeCommandHandler, false)
